### PR TITLE
Stop altering Test::More's export list permanently

### PR DESCRIPTION
**Pull request by 2shortplanks**
Addresses RT#73299

### CODE REVIEW

**Comment by mschout** [comment]
I ran into this today, using `Test::Mojo::WithRoles` along with `Test::Most`, and I can confirm that this PR fixes the issue.  Would love to see this merged.

**Comment by barefootcoder** [comment]
I agree that this solution seems both simple and effective.  @Ovid ?

**Comment by Ovid** [comment]
My apologies. I've recently cleared up a lot of filters in my email and I've found that I previously was getting some shifted to folders I wasn't expecting. Seems I've a lot of stuff on Github I've missed.

**Comment by mschout** [comment]
Thanks @Ovid!

**Pull request merged**
